lamassu/lamassu-server

package.json
Resolves issue experienced with lamassu-coinbase module: https://github.com/lamassu/lamassu-coinbase/issues/4
=> 2.2.6, fixes wreck to 5.1.0,

bin/lamassu-update, package.json
Without --allow-root, when running the terminal streams an endless:
```
gyp WARN EACCES user "root" does not have permission to access the dev dir...
```
=> Update lamassu-update, add to bin

bin/lamassu-cancel, lib/blockchain/common.js
Point to new cash-out-tx library location.
=> Fix lamassu-cancel

lib/blockchain/common.js
Resolves lock-up during initial sync: https://github.com/ethereum/go-ethereum/pull/16546
=> Update geth & Bitcoin ABC

migrations/1526034901860-crypto_atoms_to_numeric.js
Addresses: https://github.com/lamassu/lamassu-server/issues/115
=> change crypto_atoms to numeric in db to support ETH

public/elm.js
Relates to https://github.com/lamassu/lamassu-admin-elm/pull/5
=> customer.sanctions field type fix

public/elm.js, public/lamassu-elm.js, public/styles.css
Relates to https://github.com/lamassu/lamassu-admin-elm/pull/4
=> Terms and conditions screen fix

install, lib/plugins/layer2/strike/strike.js, package-lock.json, package.json
https://github.com/lodash/lodash/commit/c6f8896826a82d894e0335e78e42d8d8f80bb87a
=> Strike bugfix

dev/json-rpc.js, lib/plugins/common/json-rpc.js
```
gor error Error: json-rpc::axios error: Request failed with status code 500 
at Promise.resolve.then.then.catch.err (/Users/fabio/Documents/lu/lamassu-server/lib/plugins/common/json-rpc.js:31:13)
at <anonymous>
at process._tickCallback (internal/process/next_tick.js:182:7)
Process finished with exit code 0
```
=> json-rpc error handling

dev/json-rpc.js, lib/plugins/common/json-rpc.js
=> json-rpc parameter bugfix

bin/lamassu-update
https://trello.com/c/OV82SnDv/504-operator-server-upgrade-script-to-deploy-latest-changes
=> lamassu-update script changes to update supervisor config

lib/routes.js
lib/compliance.js has a different signature
```
function validationPatch (deviceId, config, customer) {
```
=> compliance router fix

lib/compliance.js, lib/ofac/index.js, package-lock.json, package.json
https://trello.com/c/xDhnNOaq/572-blocked-customer-flow-on-cash-out-invokes-cash-in-screens
=> OFAC flow fix

languages.json
Fixes lack of 'hy-AM' in admin's Setup panel.
=> Add Armenian to languages.json

lib/blockchain/common.js, lib/blockchain/zcash.js
=> Wallet version updates

lib/admin/admin-server.js, public/elm.js, public/lamassu-elm.js, public/styles.css
Relies on #151
Relates to https://github.com/lamassu/lamassu-admin-elm/pull/6
=> Id card photo admin server changes

lib/layer2.js
I was condering if it is the case of giving the error anyway (in the logs).
Otherwise I can just fix with
```if (_.defaultTo('no-layer2', plugin) === 'no-layer2') return Promise.resolve()```
=> layer2 default fix

public/elm.js, public/lamassu-elm.js, public/styles.css
Relies on https://github.com/lamassu/lamassu-admin-elm/pull/7
=> elm changes on config screen

bin/lamassu-update, lib/app.js
it was failing to retry when starting with an invalid configuration
=> reworking l-s startup

lib/blockchain/install.js
card: https://trello.com/c/3fMfHclE
Unfortunately, Inquirer.js API does not provide signatures to change Initial instructions as requested on card. Can we live with this?
=> 7.3 crafty chhnemu | https://trello.com/c/3fMfHclE

lib/blockchain/install.js
GUI output is performing as expected, however, coins installation still proceeds for Geth deamon install. Corrected the behaviour.
=> Drop Geth installation upon coins installation

lib/pairing.js, lib/routes.js
=> Identify machine name on server log upon machine clock skew error

lib/customers.js
List 1000 customers instead of 20.
=> Expand customer results

lib/coinatmradar/coinatmradar.js
=> Fix coinATMRadar behaviour when null cash out value is received

lib/admin/config.js
Rename 'Mock ticker' to 'Mock (Caution!)'
=> Caution against mock-ticker use
