lamassu/lamassu-server

- lib/admin/config.js
- lib/plugins/ticker/bitpay/bitpay.js
Bitpay now provides a BCH ticker, and will be more reliable than Kraken.
> Add Bitpay ticker for BCH

- lib/blockchain/common.js
- lib/blockchain/zcash.js
This version of Bitcoin ABC includes CashAddr support (default).
> Update node wallet versions

- lib/plugins/exchange/kraken/kraken.js
If a machine currency is other than USD or EUR, Kraken trades will fail because pair is not defined in `common/kraken.js` (and not offered by Kraken).
Instead, trade on USD market.
> Trade on USD Kraken if fiat is other than USD/EUR

- lib/blockchain/common.js
- lib/blockchain/ethereum.js
As we're recommending a 16 GB RAM droplet for ETH, we have overhead to increase the cache usage during syncing and to increase peer connections (default is 25).
Whereas fast mode on 1.8.0 with 500 MB cache / 25 peers would not keep in sync (see https://github.com/ethereum/go-ethereum/issues/15001), increasing RAM usage to 2 GB and allowing up to 40 peers allowed full sync in under a half-day and subsequently stayed in sync.
> ETH performance

- lib/blockchain/common.js
- lib/blockchain/ethereum.js
Corrects `maxconnections` to `maxpeers`, updates geth to 1.8.1.
> Fix ETH peers and bump to 1.8.1

- lib/routes.js
When an incorrect phone number is given, lamassu-machine expects a 401 error code, but lamassu-server was returning 410 instead, leading to machine hangs in the 'waiting' state.
> Fix BadNumberError code

- lib/admin/config.js
- lib/coin-utils.js
- lib/plugins/wallet/bitcoincashd/bitcoincashd.js
- lib/plugins/wallet/bitcoind/bitcoind.js
Remove BCH address conversion to support CashAddr format natively.
Switch machine display back to 'Bitcoin Cash'. No need to avoid confusion as we're only allowing for CashAddr at the machine.
> Support CashAddr format

- lib/blockchain/common.js
- lib/blockchain/zcash.js
ZEC will hardfork upgrade on 25 June. v1.1.0 is compatible with new consensus changes.
BCH will hardfork upgrade on 15 May. v0.17.0 is compatible with new consensus changes.
ETH update to address network DoS attacks.
> Update ZEC & BCH for hardforks, ETH release

- lib/plugins/ticker/bitstamp/bitstamp.js
Employs the method we use for Kraken when machine currency is other than EUR or USD.
> Use forex conversion on Bitstamp

- migrations/migrate-tools.js
Don't fail with duplicate key errors if there is more than one row already in the devices table, since it attempts to update the device_id column.
> Fix migrate-tools for multiple devices

- lib/routes.js
This was causing
`error: TypeError: Cannot read property 'sanctionsOverride' of undefined
at validateOfac (lamassu-server/lib/compliance.js:63:16)
at Object.validationPatch (lamassu-server/lib/compliance.js:71:10)
at customers.get.then.then.customer (lamassu-server/lib/routes.js:183:25)
at <anonymous>`
> phone_code API bugfix

- schemas/twilio.json
The placeholder number is being consistently mistaken as belonging there. Better to leave it off, and specify 'international format' here and in documentaiton.
'From' and 'To' can be rendered more descriptive as 'Twilio' and 'Notifications' numbers.
> Remove sample format on Twilio panel

- lib/admin/config.js
If mock wallet is used in production on a two-way machine, would allow for dispensing cash without sending coins. Add 'caution' to the admin (in addition to current warnings in support documentation).
> Add 'caution' warning to mock wallet

- dev/send-message.js
- lib/plugins/sms/mock-sms/mock-sms.js
- lib/plugins/sms/twilio/twilio.js
This is to:
- Fix any configuration error that wasn't sent within the Promise context because it was crashing here https://github.com/lamassu/lamassu-server/compare/staging...lidio601:sms-integration-fix?expand=1#diff-69df051a0a40f600c077ad5f90babb52L10
- Added the change to have an error by the mock-sms integration by sending '666' as phone number 👿
> Sms integration fix

- bin/cert-gen.sh
- install
- lamassu-default.json
- lib/admin/admin-server.js
- lib/admin/config.js
- lib/config-validate.js
- lib/migrate-options.js
This is to solve https://gist.github.com/naconner/1f1e668ca69039675f581efcb602423d#file-gistfile1-txt-L73
To test you can take the last user_config and remove all the terms related configs from the array.
Then when you start l-a server you'll see the config-validator error.
This change is to make it consider also defaults from the schema in case the config value is missing (like in this case when we were migrating from an old version)
> config-validator to consider default values from schema

- lib/blockchain/common.js
Updates BTC, BCH, LTC, DASH for CVE-2018-17144.
Updates ETH to latest.
> Patch bitcoind-inhereted network vulnerability

- schemas/infura.json
API key and endpoint are less sensistive, and leaving these two displayed would allow accidental typos, such extraneous spaces, to be caught.
> Change Infura credential fieldType

- bin/lamassu-update
reset the terminal when linking/unlinking new exes
> lamassu-update minor fix

- bin/lamassu-update
Disable post-SSH logon prompts to take upgrade actions which could break the server.
> Disable motd scripts

- lib/blockchain/dash.js
Keep the Dash blockchain pruned (4.7G).
> Prune Dash

- bin/cert-gen.sh
The intended domain/IP can be provided as an argument to the bash script.
Example: `$ bash bin/cert-gen.sh 192.168.1.1`
The lack of such argument will default to the previous value: `localhost`.
> Allow the domain to be configurable when generating developer certificates
